var $ = require('jquery')
  , homepage = require('./homepage')
  //, gallery = require('./gallery')({ user: 'mvrtpicasa' })
  , dynamic = require('./dynamic')
  , doc = require('./document')
  , redirect = require('./redirect')
  , blog = require('./blog')

$(function () {
  redirect()
  homepage.init()
  dynamic.init()
  //gallery.init()
  require('./gallery')
  doc.init()
  blog.init()
})
