var $ = require('jquery')
  , homepage = require('./homepage')
  , gallery = require('./gallery')
  , dynamic = require('./dynamic')
  , doc = require('./document')
  , redirect = require('./redirect')
  , blog = require('./blog')

$(function () {
  redirect()
  homepage.init()
  dynamic.init()
  if ($('.gallery').length) gallery.init()
  doc.init()
  blog.init()
})
